const addShortcuts = require('./addShortcuts')
const addKeyboardLayout = require('./addKeyboardLayout')
const addKeyboards = require('./addKeyboards')
const addNotificationsSettings = require('./addNotificationsSettings')
const addPanelSettings = require('./addPanelSettings')
const addPowerManagerSettings = require('./addPowerManagerSettings')
const addScreenSaverSettings = require('./addScreenSaverSettings')
const addSessionSettings = require('./addSessionSettings')
const { positiveInfo } = require('../../helpers')

module.exports = async function setUpXfce () {
  await addShortcuts()
  positiveInfo('addHotkeys finished.')
  await addKeyboardLayout()
  positiveInfo('addKeyboardLayout finished.')
  await addKeyboards()
  positiveInfo('addKeyboards finished.')
  await addNotificationsSettings()
  positiveInfo('addNotificationsSettings finished.')
  await addPanelSettings()
  positiveInfo('addPanelSettings finished.')
  await addPowerManagerSettings()
  positiveInfo('addPanelSettings finished.')
  await addScreenSaverSettings()
  positiveInfo('addScreenSaverSettings finished.')
  await addSessionSettings()
  positiveInfo('addSessionSettings finished.')
}