const { createFile } = require('../../helpers')
const { path: addShortcutsPath, body: addShortcutsBody } = require('./meta/xfce4KeyboardShortcuts')
const { path: addKeyboardLayoutPath, body: addKeyboardLayoutBody } = require('./meta/keyboardLayout')
const { path: addKeyboardsPath, body: addKeyboardsBody } = require('./meta/keyboards')
const { path: addNotificationsSettingsPath, body: addNotificationsSettingsBody } = require('./meta/xfce4Notifyd')
const { path: addPanelSettingsPath, body: addPanelSettingsBody } = require('./meta/xfce4Panel')
const { path: addPowerManagerSettingsPath, body: addPowerManagerSettingsBody } = require('./meta/xfce4PowerManager')
const { path: addScreenSaverSettingsPath, body: addScreenSaverSettingsBody } = require('./meta/xfce4Screensaver')
const { path: addSessionSettingsPath, body: addSessionSettingsBody } = require('./meta/xfce4Session')

module.exports = async function setUpXfce () {
  await createFile(addShortcutsPath, addShortcutsBody)
  await createFile(addKeyboardLayoutPath, addKeyboardLayoutBody)
  await createFile(addKeyboardsPath, addKeyboardsBody)
  await createFile(addNotificationsSettingsPath, addNotificationsSettingsBody)
  await createFile(addPanelSettingsPath, addPanelSettingsBody)
  await createFile(addPowerManagerSettingsPath, addPowerManagerSettingsBody)
  await createFile(addScreenSaverSettingsPath, addScreenSaverSettingsBody)
  await createFile(addSessionSettingsPath, addSessionSettingsBody)
}