const preparePackageManagers = require('./preparePackageManagers')
const installGPUDrivers = require('./installGPUDrivers')
const installZsh = require('./installZsh')
const installJavaForIdea = require('./installJavaForIdea')
const installNodeJs = require('./installNodeJs')
const autoLoginLightdm = require('./autoLoginLightdm')
const updateGrubTimer = require('./updateGrubTimer')
const backupFstab = require('./backupFstab')
const addSwap = require('./addSwap')

module.exports = async function setUpSystem () {
  await preparePackageManagers()
  await installZsh()
  await installGPUDrivers()
  await installJavaForIdea()
  await backupFstab()
  await addSwap()
  await autoLoginLightdm()
  await updateGrubTimer()
  await installNodeJs()
}