const preparePackageManagers = require('./preparePackageManagers')
const installGPUDrivers = require('./installGPUDrivers')
const installZsh = require('./installZsh')
const installJavaForIdea = require('./installJavaForIdea')
const installNodeJs = require('./installNodeJs')
const autoLoginLightdm = require('./autoLoginLightdm')
const updateGrubTimer = require('./updateGrubTimer')
const backupFstab = require('./backupFstab')
const addSwap = require('./addSwap')
const { positiveInfo } = require('../../helpers')

module.exports = async function setUpSystem () {
  await preparePackageManagers()
  positiveInfo('preparePackageManagers finished.')
  await installZsh()
  positiveInfo('installZsh finished.')
  await installGPUDrivers()
  positiveInfo('installGPUDrivers finished.')
  await installJavaForIdea()
  positiveInfo('installJavaForIdea finished.')
  await backupFstab()
  positiveInfo('backupFstab finished.')
  await addSwap()
  positiveInfo('addSwap finished.')
  await autoLoginLightdm()
  positiveInfo('autoLoginLightdm finished.')
  await updateGrubTimer()
  positiveInfo('updateGrubTimer finished.')
  await installNodeJs()
  positiveInfo('installNodeJs finished.')
}